---
- hosts: all
  sudo: true
  gather_facts: true
  vars_files:
    - variables.yml

  tasks:

    - name: Set enviroment variables
      lineinfile: dest=/etc/environment state=present regexp="{{ item.key }}" line="{{ item.value }}"
      with_items:
        - { key: '^BPS_JEESERVER_HOME', value : 'BPS_JEESERVER_HOME=/var/lib/tomcat6/' }
        - { key: '^BPS_WEBROOT', value : 'BPS_WEBROOT=/var/www/{{ project_name }}' }
        - { key: '^DB_USER', value : 'DB_USER={{ db_user }}'}
        - { key: '^DB_PASSWORD', value : 'DB_PASSWORD={{ db_password }}'}
        - { key: '^DB_PASSWORD_BPS', value : 'DB_PASSWORD_BPS={{ db_password }}'}
        - { key: '^BPS_CORPORA', value : 'BPS_CORPORA={{ project_root }}/corpora'}
        - { key: '^CLASSPATH', value : 'CLASSPATH=/usr/share/java/mysql.jar'}
      notify: source environment

    - name: Build WAR with maven
      shell: mvn clean install -DskipTests chdir={{ code_root }}/code/bps/services
      #ignore_errors: yes
      environment:
        JAVA_HOME: /usr/lib/jvm/java-6-openjdk-amd64
        BPS_JEESERVER_HOME: /var/lib/tomcat6/
        BPS_WEBROOT: "/var/www/{{ project_name }}"
        DB_USER: "{{ db_user }}"
        DB_PASSWORD: "{{ db_password }}"
        DB_PASSWORD_BPS: "{{ db_password }}"
        BPS_CORPORA : "{{ project_root }}/corpora"
        CLASSPATH: /usr/share/java/mysql.jar:$CLASSPAT
      notify: restart tomcat
        
  handlers:
  - name: restart tomcat
    service: name=tomcat6 state=restarted
    environment:
      JAVA_HOME: /usr/lib/jvm/java-6-openjdk-amd64
      BPS_JEESERVER_HOME: /var/lib/tomcat6/
      BPS_WEBROOT: "/var/www/{{ project_name }}"
      DB_USER: "{{ db_user }}"
      DB_PASSWORD: "{{ db_password }}"
      DB_PASSWORD_BPS: "{{ db_password }}"
      BPS_CORPORA : "{{ project_root }}/corpora"
      CLASSPATH: /usr/share/java/mysql.jar:$CLASSPATH