---
- hosts: all
  sudo: true
  gather_facts: true
  vars_files:
    - variables.yml

  tasks:

    - name: Set enviroment variables
      lineinfile: dest=/etc/environment state=present regexp="{{ item.key }}" line="{{ item.value }}"
      with_items:
        - { key: '^BPS_JEESERVER_HOME', value : 'BPS_JEESERVER_HOME=/var/lib/tomcat6/' }
        - { key: '^BPS_WEBROOT', value : 'BPS_WEBROOT=/var/www/{{ project_name }}' }
        - { key: '^DB_USER', value : 'DB_USER={{ db_user }}'}
        - { key: '^DB_PASSWORD', value : 'DB_PASSWORD={{ db_password }}'}
        - { key: '^DB_PASSWORD_BPS', value : 'DB_PASSWORD_BPS={{ db_password }}'}
        - { key: '^BPS_CORPORA', value : 'BPS_CORPORA={{ project_root }}/corpora'}
        - { key: '^CLASSPATH', value : 'CLASSPATH=/usr/share/java/mysql.jar'}
      notify: source environment

    - name: Ensure Mysql is running
      service: name=mysql state=running

    - name: Set user privileges
      mysql_user:
        login_host: 127.0.0.1
        login_port: 3306
        login_user: "root"
        login_password: "{{db_password}}"
        user: "{{db_user}}"
        password: "{{db_password}}"
        priv: "*.*:ALL,GRANT"
        state: present
        check_implicit_admin: True


    - name: Create missing db directory
      file: path={{project_root}}/bps/code/bps/services/common/target/db state=directory

    - name: Copy db init file
      copy: src=files/db/initdb.sql  dest={{ project_root }}/bps/code/bps/services/common/target/db/initdb.sql

    - name: Create the DB
      shell: ant create_db chdir={{ project_root }}/bps/code/bps/services
      environment:
        JAVA_HOME: /usr/lib/jvm/java-6-openjdk-amd64
        BPS_JEESERVER_HOME: /var/lib/tomcat6/
        BPS_WEBROOT: "/var/www/{{ project_name }}"
        DB_USER: "{{ db_user }}"
        DB_PASSWORD: "{{ db_password }}"
        DB_PASSWORD_BPS: "{{ db_password }}"
        BPS_CORPORA : "{{ project_root }}/corpora"
        CLASSPATH: /usr/share/java/mysql.jar:$CLASSPATH
      notify: restart_mysql

  handlers:

  - name: restart_mysql
    service: name=mysql state=started